services:
  mongodb:
    image: mongo
    volumes:
      - "./db:/data/db"
    ports:
      - 27017:27017
    attach: false

  girder:
    build:
      context: ./devops/girder
    privileged: true
    command: -c "python3 /src/provision.py && girder mount /mnt/fuse && celery -A girder_worker.app worker -Q local -D && uvicorn girder.asgi:app --host 0.0.0.0 --port 8080"
    ports:
      - "${GIRDER_PORT-8080}:8080"
    links:
      - mongodb
      - redis
    volumes:
      # For some versions of Docker on OSX, adding delegated speeds up file
      # access.  It should do no harm on other systems.
      - "./assetstore:/assetstore:delegated"
      - "./logs/girder:/root/.girder/logs:delegated"
      - '/var/run/docker.sock:/var/run/docker.sock'
    env_file:
      - "./girder.env"
      - "./worker.env"
    environment:
      - ZENODO_ENCRYPTION_KEY=${ZENODO_ENCRYPTION_KEY:-}
    depends_on:
      - "mongodb"
      - "broker"
    container_name: "girder"

  redis:
    image: redis:latest
    command: ["redis-server", "--maxmemory", "4096MB", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - redis_data:/data

  broker:
    image: rabbitmq:3
    attach: false
    env_file:
    - "./worker.env"

  worker:
    image: girder/girder_worker
    links:
      - girder
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - broker
    container_name: "worker"
    user: root
    env_file:
    - "./worker.env"

volumes:
  redis_data:
