"""Parity tests: the pure-Python multi-source pipeline must reproduce the
frontend goldens byte-for-byte (deep equality; JSON key order irrelevant).

Fixtures live in ``test/parity_fixtures/*.json`` and are generated by the
real Vue component / parsing code (a separate frontend harness). This test
only needs the standard library plus the ported helpers -- no Girder
server -- so the helpers are imported directly from the ``server``
directory.

Fixture kinds:
* ``parsing_*.json`` -- ``collect_filename_metadata(filenames)`` must equal
  ``expected.variables``.
* everything else -- run ``compute_configuration`` and compare ``config``,
  ``dimensionLabels``, ``transcodeDefault``, ``defaultAssignments`` (from
  ``get_default_assignments`` BEFORE any strategy is applied) and
  ``filenameVariables`` (``collect_filename_metadata`` when >1 item, else
  ``[]``).

If the fixtures directory is missing or a fixture lacks an ``expected``
block, that case is skipped with a clear reason (goldens not generated).
"""

import glob
import json
import os
import sys

import pytest

_HERE = os.path.dirname(os.path.abspath(__file__))
_SERVER = os.path.abspath(os.path.join(_HERE, "..", "server"))
if _SERVER not in sys.path:
    sys.path.insert(0, _SERVER)

from helpers.filename_parsing import collect_filename_metadata  # noqa: E402
from helpers.multi_source import (  # noqa: E402
    build_dimensions,
    compute_configuration,
    get_default_assignments,
)

_FIXTURE_DIR = os.path.join(_HERE, "parity_fixtures")


def _fixture_paths():
    if not os.path.isdir(_FIXTURE_DIR):
        return []
    return sorted(glob.glob(os.path.join(_FIXTURE_DIR, "*.json")))


def _fixture_id(path):
    return os.path.splitext(os.path.basename(path))[0]


_PATHS = _fixture_paths()


def _roundtrip(obj):
    """Normalize through JSON so tuples/ints compare like the goldens."""
    return json.loads(json.dumps(obj))


def _default_assignments_summary(dimensions):
    defaults = get_default_assignments(dimensions)
    summary = {}
    for dim in ("XY", "Z", "T", "C"):
        chosen = defaults[dim]
        summary[dim] = (
            {"source": chosen["source"], "guess": chosen["guess"]}
            if chosen else None
        )
    return summary


@pytest.mark.skipif(
    not _PATHS,
    reason="parity_fixtures directory missing (goldens not yet generated)",
)
@pytest.mark.parametrize("path", _PATHS, ids=_fixture_id)
def test_parity(path):
    with open(path, encoding="utf-8") as handle:
        fixture = json.load(handle)

    expected = fixture.get("expected")
    if not expected:
        pytest.skip("fixture has no 'expected' block (golden not generated)")

    inp = fixture["input"]
    name = _fixture_id(path)

    if name.startswith("parsing_"):
        actual = _roundtrip(collect_filename_metadata(inp["filenames"]))
        assert actual == expected["variables"]
        return

    if "config" not in expected:
        pytest.skip("fixture has no 'config' in expected (not a config case)")

    item_names = inp["itemNames"]
    tiles_metadata = inp["tilesMetadata"]
    internal_metadata = inp["tilesInternalMetadata"]
    options = inp.get("options") or {}
    strategy = options.get("assignmentStrategy")

    result = compute_configuration(
        item_names,
        tiles_metadata,
        internal_metadata,
        strategy=strategy,
        split_rgb_bands=options.get("splitRGBBands", True),
        enable_compositing=options.get("enableCompositing", False),
    )

    # defaultAssignments is computed from defaults, independent of strategy.
    built = build_dimensions(item_names, tiles_metadata)
    default_assignments = _default_assignments_summary(built["dimensions"])

    filename_variables = (
        _roundtrip(collect_filename_metadata(item_names))
        if len(item_names) > 1 else []
    )

    assert _roundtrip(result["config"]) == expected["config"]
    assert _roundtrip(result["dimensionLabels"]) == \
        expected["dimensionLabels"]
    assert result["transcodeDefault"] == expected["transcodeDefault"]
    assert default_assignments == expected["defaultAssignments"]
    assert filename_variables == expected["filenameVariables"]
