"""Parity tests: the pure-Python multi-source pipeline must reproduce the
frontend goldens byte-for-byte (deep equality; JSON key order irrelevant).

Fixtures live in ``test/parity_fixtures/*.json`` and are generated by the
real Vue component / parsing code (a separate frontend harness). This test
only needs the standard library plus the ported helpers -- no Girder
server -- so the helpers are imported directly from the ``server``
directory.

Fixture kinds:
* ``parsing_*.json`` -- ``collect_filename_metadata(filenames)`` must equal
  ``expected.variables``.
* ``kind: "validation"`` -- the component *refuses* these inputs; the
  validators must raise ``ValueError`` with the component's exact
  ``submitError`` text (and in the same precedence order).
* everything else -- run ``compute_configuration`` and compare ``config``,
  ``dimensionLabels``, ``transcodeDefault``, ``defaultAssignments`` (from
  ``get_default_assignments`` BEFORE any strategy is applied) and
  ``filenameVariables`` (``collect_filename_metadata`` when >1 item, else
  ``[]``).

If the fixtures directory is missing or a fixture lacks an ``expected``
block, that case is skipped with a clear reason (goldens not generated).
"""

import glob
import json
import os
import sys

import pytest

_HERE = os.path.dirname(os.path.abspath(__file__))
_SERVER = os.path.abspath(os.path.join(_HERE, "..", "server"))
if _SERVER not in sys.path:
    sys.path.insert(0, _SERVER)

from helpers.filename_parsing import collect_filename_metadata  # noqa: E402
from helpers.multi_source import (  # noqa: E402
    build_dimensions,
    compute_configuration,
    get_default_assignments,
    validate_assignments,
    validate_source_dtypes,
)

_FIXTURE_DIR = os.path.join(_HERE, "parity_fixtures")


def _fixture_paths():
    if not os.path.isdir(_FIXTURE_DIR):
        return []
    return sorted(glob.glob(os.path.join(_FIXTURE_DIR, "*.json")))


def _fixture_id(path):
    return os.path.splitext(os.path.basename(path))[0]


_PATHS = _fixture_paths()


def _roundtrip(obj):
    """Normalize through JSON so tuples/ints compare like the goldens."""
    return json.loads(json.dumps(obj))


def _default_assignments_summary(dimensions):
    defaults = get_default_assignments(dimensions)
    summary = {}
    for dim in ("XY", "Z", "T", "C"):
        chosen = defaults[dim]
        summary[dim] = (
            {"source": chosen["source"], "guess": chosen["guess"]}
            if chosen else None
        )
    return summary


def _assert_validation_parity(inp, expected):
    """The validators must reproduce the component's ``submitError``.

    The frontend's own precedence is
    ``mixedSourceDtypeError ?? assignmentError``, so the dtype check runs
    first here too -- the ``*_precedence`` fixture is what pins that order.

    Only the *message* is parity-checked, deliberately: the two ends do not
    behave the same way. ``submitError`` merely disables the UI's Submit
    button, and ``validation_incomplete_assignments``'s golden records
    ``configUploaded: true`` to prove ``generateJson`` still runs when it
    is set. The API has no disabled button, so it turns the same condition
    into a hard 400 (or, under dryRun, a ``validationError`` field). Do not
    "fix" either side to match the other.
    """
    item_names = inp["itemNames"]
    tiles_metadata = inp["tilesMetadata"]
    options = inp.get("options") or {}
    split_rgb_bands = options.get("splitRGBBands", True)

    result = compute_configuration(
        item_names,
        tiles_metadata,
        inp["tilesInternalMetadata"],
        strategy=options.get("assignmentStrategy"),
        split_rgb_bands=split_rgb_bands,
        enable_compositing=options.get("enableCompositing", False),
    )

    error = None
    try:
        validate_source_dtypes(tiles_metadata)
        validate_assignments(
            result["variables"], result["assignments"],
            result["isRGBFile"] and result["rgbBandCount"] > 1,
            split_rgb_bands,
        )
    except ValueError as exc:
        error = str(exc)

    assert error == expected["submitError"]


@pytest.mark.skipif(
    not _PATHS,
    reason="parity_fixtures directory missing (goldens not yet generated)",
)
@pytest.mark.parametrize("path", _PATHS, ids=_fixture_id)
def test_parity(path):
    with open(path, encoding="utf-8") as handle:
        fixture = json.load(handle)

    expected = fixture.get("expected")
    if not expected:
        pytest.skip("fixture has no 'expected' block (golden not generated)")

    inp = fixture["input"]
    name = _fixture_id(path)

    if name.startswith("parsing_"):
        actual = _roundtrip(collect_filename_metadata(inp["filenames"]))
        assert actual == expected["variables"]
        return

    if fixture.get("kind") == "validation":
        _assert_validation_parity(inp, expected)
        return

    if "config" not in expected:
        pytest.skip("fixture has no 'config' in expected (not a config case)")

    item_names = inp["itemNames"]
    tiles_metadata = inp["tilesMetadata"]
    internal_metadata = inp["tilesInternalMetadata"]
    options = inp.get("options") or {}
    strategy = options.get("assignmentStrategy")

    result = compute_configuration(
        item_names,
        tiles_metadata,
        internal_metadata,
        strategy=strategy,
        split_rgb_bands=options.get("splitRGBBands", True),
        enable_compositing=options.get("enableCompositing", False),
    )

    # defaultAssignments is computed from defaults, independent of strategy.
    built = build_dimensions(item_names, tiles_metadata)
    default_assignments = _default_assignments_summary(built["dimensions"])

    filename_variables = (
        _roundtrip(collect_filename_metadata(item_names))
        if len(item_names) > 1 else []
    )

    assert _roundtrip(result["config"]) == expected["config"]
    assert _roundtrip(result["dimensionLabels"]) == \
        expected["dimensionLabels"]
    assert result["transcodeDefault"] == expected["transcodeDefault"]
    assert default_assignments == expected["defaultAssignments"]
    assert filename_variables == expected["filenameVariables"]


def _load(name):
    with open(os.path.join(_FIXTURE_DIR, name), encoding="utf-8") as handle:
        return json.load(handle)["input"]


@pytest.mark.skipif(
    not os.path.isfile(
        os.path.join(_FIXTURE_DIR, "nd2_compositing_identity.json")
    ),
    reason="compositing fixture missing",
)
class TestCompositingCollapsesXY:
    """`compositing` in the result is not an echo of the request.

    When the sources are actually composited they are laid out by stage
    position and every ``xySet`` is forced to 0, so the configured image
    has ONE xy position however large the XY assignment was. The endpoint
    reads this flag to record the dataset's real extent in the collection's
    compatibility block -- recording the assignment size instead made
    ``areCompatibles()`` report the new collection as incompatible with the
    dataset it had just been created for.
    """

    @staticmethod
    def _run(enable_compositing):
        inp = _load("nd2_compositing_identity.json")
        return compute_configuration(
            inp["itemNames"], inp["tilesMetadata"],
            inp["tilesInternalMetadata"],
            strategy=(inp.get("options") or {}).get("assignmentStrategy"),
            split_rgb_bands=True,
            enable_compositing=enable_compositing,
        )

    def test_compositing_reported_and_xy_collapsed(self):
        result = self._run(True)
        assert result["compositing"] is True
        assert {s["xySet"] for s in result["config"]["sources"]} == {0}

    def test_not_compositing_when_not_requested(self):
        result = self._run(False)
        assert result["compositing"] is False
        # ...and then the XY assignment's size is the real extent.
        assert "xySet" not in result["config"]["sources"][0]


class TestOneVariableCanDriveTwoDimensions:
    """Pinning a surprise, so nobody "fixes" it inside the port.

    Codex flagged that an override which moves a variable to another axis,
    while omitting the axis it was originally guessed for, leaves that one
    variable on BOTH -- mapping a single filename token onto two dimensions.
    That is real, and it is what the frontend does: ``strategy_override``'s
    golden, generated by running the actual Vue component, carries both
    ``xyValues`` and ``tValues`` from one filename variable.

    The dropdowns cannot express it (``assignmentItems`` hides variables
    already assigned elsewhere), but ``applyDimensionStrategy`` -- the
    function this ports, used when a saved strategy is replayed onto the
    next dataset in a batch upload -- has no such filter. Making the backend
    reject or de-duplicate it would diverge from the component and break
    that golden, so the behaviour stays and is documented here instead. If
    it should change, it has to change in the component first.
    """

    NAMES = ["gfp_A1.tif", "red_A1.tif"]
    TILES = [
        {"bandCount": 1, "frames": [], "sizeX": 16, "sizeY": 16,
         "dtype": "uint16"},
    ] * 2

    def _run(self, strategy):
        return compute_configuration(
            self.NAMES, self.TILES, [{}, {}], strategy=strategy,
            split_rgb_bands=True, enable_compositing=False,
        )

    def test_an_omitted_dimension_keeps_its_default_even_when_shared(self):
        result = self._run({"XY": {"source": "filename", "guess": "C"}})
        assignments = result["assignments"]
        assert assignments["XY"]["name"] == "Filename variable 1"
        assert assignments["C"]["name"] == "Filename variable 1"
        # One token, two axes -- matching the component (see the golden for
        # strategy_override, which does the same with XY and T).
        for source in result["config"]["sources"]:
            assert source["xyValues"] == source["cValues"]

    def test_validation_accepts_it_as_the_component_does(self):
        result = self._run({"XY": {"source": "filename", "guess": "C"}})
        validate_assignments(
            result["variables"], result["assignments"],
            result["isRGBFile"] and result["rgbBandCount"] > 1, True,
        )

    def test_an_explicit_null_still_unassigns(self):
        """The escape hatch a caller has: name the dimension as null rather
        than omitting it."""
        result = self._run({
            "XY": {"source": "filename", "guess": "C"}, "C": None,
        })
        assert result["assignments"]["C"] is None
        for source in result["config"]["sources"]:
            assert "cValues" not in source


class TestRgbLayoutComesFromTheFirstSourceOnly:
    """Pinning a shared gap, so it is not "fixed" only in the port.

    The RGB decision is taken from ``tiles_metadata[0]`` alone, matching
    ``MultiSourceConfiguration.vue``:

        const firstItem = tilesMetadata.value[0];
        rgbBandCount.value = firstItem?.bandCount || 0;
        isRGBFile.value = detectColorVsChannels(firstItem);

    So a folder whose first item is RGB and whose second is grayscale asks
    every source for bands 1-3, and the grayscale one has no bands 2 or 3.
    That is a real defect -- filed as issue #1325 -- but it belongs in the
    component first: rejecting it here would make the API refuse folders the
    UI accepts, and the guard should read like ``mixedSourceDtypeError``,
    with a parity fixture pinning the message on both sides.

    When #1325 lands in the component, this test is what should fail.
    """

    def test_first_source_decides_for_the_whole_folder(self):
        rgb = {"bandCount": 3, "frames": [], "sizeX": 16, "sizeY": 16,
               "dtype": "uint8"}
        grey = {"bandCount": 1, "frames": [], "sizeX": 16, "sizeY": 16,
                "dtype": "uint8"}
        result = compute_configuration(
            ["a_colour.tif", "b_mono.tif"], [rgb, grey], [{}, {}],
            strategy=None, split_rgb_bands=True, enable_compositing=False,
        )
        assert result["isRGBFile"] is True
        assert result["rgbBandCount"] == 3
        # Both sources get band styling, including the grayscale one.
        byPath = {}
        for source in result["config"]["sources"]:
            byPath.setdefault(source["path"], []).append(
                source["style"]["bands"][0]["band"]
            )
        assert byPath["b_mono.tif"] == [1, 2, 3], (
            "if this changed, the component grew the guard from #1325 and "
            "this port needs to follow it"
        )

    def test_the_dtype_guard_does_not_cover_it(self):
        """Same pixel type, different band layout: nothing rejects it."""
        rgb = {"bandCount": 3, "frames": [], "sizeX": 16, "sizeY": 16,
               "dtype": "uint8"}
        grey = {"bandCount": 1, "frames": [], "sizeX": 16, "sizeY": 16,
                "dtype": "uint8"}
        validate_source_dtypes([rgb, grey])
