name: Lint and test backend

on:
  push:
    paths:
      - devops/girder/**

jobs:
  all:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: latest
      - name: Test AnnotationPlugin
        run: pip install tox && cd devops/girder/plugins/AnnotationPlugin && tox
      - name: Test Claude plugins
        run: pip install tox && cd devops/girder/plugins/girder_claude_chat && tox