name: Build, lint and test frontend

on: [push]

jobs:
  all:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Typescript check
        run: pnpm tsc
      - name: Vue linter
        run: pnpm lint:ci
        env:
          NODE_ENV: production
      - name: Build frontend
        run: pnpm build
      - name: Run frontend tests
        run: pnpm test
